version: "3.8"

services:
  postgres:
    image: timescale/timescaledb-ha:pg16
    container_name: nsac_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-airquality}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      # Persist database data
      - postgres_data:/var/lib/postgresql/data
      # Mount initialization scripts (auto-run on first container start)
      - ./init-scripts:/docker-entrypoint-initdb.d
      # Optional: mount setup script for manual execution if needed
      - ../data-processing/setup_database.sql:/scripts/setup_database.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-airquality}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nsac_network

  # Optional: pgAdmin for database management (web UI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nsac_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@nsac.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - nsac_network
    profiles:
      - tools # Only starts when using --profile tools

volumes:
  postgres_data:
    name: nsac_postgres_data
  pgadmin_data:
    name: nsac_pgadmin_data

networks:
  nsac_network:
    name: nsac_network
    driver: bridge
